election 3/Models/Debates.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace election_3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Debates
    {
        public int DebateID { get; set; }
        public string DebateTitle { get; set; }
        public System.DateTime DebateDate { get; set; }
        public string Location { get; set; }
        public int Candidate1ID { get; set; }
        public int Candidate2ID { get; set; }
        public string Description { get; set; }
        public Nullable<bool> Status { get; set; }
    }
}

election 3/Controllers/DebatesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using election_3.Models;

namespace election_3.Controllers
{
    public class DebatesController : Controller
    {
        private electionEntities2 db = new electionEntities2();

        // GET: Debates
        public ActionResult Index()
        {

            return View(db.Debates.ToList());
        }
        public ActionResult AdminDebates()
        {

            return View();
        }

        // GET: Debates/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            var debates = db.Debates.Find(id);
            if (debates == null)
            {
                return HttpNotFound();
            }
            return View(debates);
        }

        // GET: Debates/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Debates/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "DebateID,DebateTitle,DebateDate,Location,Candidate1ID,Candidate2ID,Description")] Debates debates)
        {
            if (ModelState.IsValid)
            {
                db.Debates.Add(debates);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(debates);
        }

        // GET: Debates/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Debates debates = db.Debates.Find(id);
            if (debates == null)
            {
                return HttpNotFound();
            }
            return View(debates);
        }

        // POST: Debates/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "DebateID,DebateTitle,DebateDate,Location,Candidate1ID,Candidate2ID,Description")] Debates debates)
        {
            if (ModelState.IsValid)
            {
                db.Entry(debates).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(debates);
        }

        // GET: Debates/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Debates debates = db.Debates.Find(id);
            if (debates == null)
            {
                return HttpNotFound();
            }
            return View(debates);
        }

        // POST: Debates/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Debates debates = db.Debates.Find(id);
            db.Debates.Remove(debates);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

election 3/Views/Debates/About.cshtml
@model election_3.Models.Debates

@{
    ViewBag.Title = "About";
}

<h2>About</h2>

election 3/Views/Debates/Create.cshtml
@model election_3.Models.Debates

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Debates</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.DebateTitle, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.DebateTitle, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.DebateTitle, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.DebateDate, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.DebateDate, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.DebateDate, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Location, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Location, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Location, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Candidate1ID, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Candidate1ID, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Candidate1ID, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Candidate2ID, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Candidate2ID, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Candidate2ID, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Description, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Description, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

election 3/Views/Debates/Delete.cshtml
@model election_3.Models.Debates

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Debates</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.DebateTitle)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DebateTitle)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.DebateDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DebateDate)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Location)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Location)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Candidate1ID)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Candidate1ID)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Candidate2ID)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Candidate2ID)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Description)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Description)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

election 3/Views/Debates/Details.cshtml
@model election_3.Models.Debates

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>Debates</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.DebateTitle)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DebateTitle)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.DebateDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DebateDate)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Location)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Location)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Candidate1ID)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Candidate1ID)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Candidate2ID)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Candidate2ID)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Description)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Description)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.DebateID }) |
    @Html.ActionLink("Back to List", "Index")
</p>

election 3/Views/Debates/Edit.cshtml
@model election_3.Models.Debates

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Debates</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.DebateID)

        <div class="form-group">
            @Html.LabelFor(model => model.DebateTitle, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.DebateTitle, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.DebateTitle, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.DebateDate, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.DebateDate, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.DebateDate, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Location, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Location, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Location, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Candidate1ID, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Candidate1ID, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Candidate1ID, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Candidate2ID, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Candidate2ID, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Candidate2ID, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Description, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Description, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

election 3/Views/Debates/Index.cshtml
 you avoid the NullReferenceException related to _context.

@model IEnumerable<election_3.Models.Debates>

@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>


<!DOCTYPE html>
<html lang="ar">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title</title>
    <link rel="stylesheet" href="~/Content/site.css"> <!-- اضمن أن الملف موجود في مجلد Content -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css"> <!-- يمكنك استخدام Bootstrap للتنسيق -->
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-lg navbar-light bg-light">
            <a class="navbar-brand" href="#">الصفحة الرئيسية ( مناظرات)</a>
        </nav>
    </header>

    <div class="container mt-4">
        <div class="row">
            <!-- البطاقة 1 -->
            <div class="col-md-4">
                <div class="card">
                    <div class="card-body text-center">
                        <i class="fas fa-rocket fa-3x mb-3"></i> <!-- أيقونة -->
                        <h5 class="card-title">
                            Overview of the importance of debates.
                        </h5>
                        <p class="card-text">تفاصيل المناظرة الرئاسية القادمة وكيفية متابعة الأحداث.</p>
                        <a href="https://ar.wikipedia.org/wiki/%D9%85%D9%86%D8%A7%D8%B8%D8%B1%D8%A9" class="btn btn-primary">اقرأ المزيد</a> <!-- رابط للتفاصيل -->
                    </div>
                </div>
            </div>

            <!-- البطاقة 2 -->
            <div class="col-md-4">
                <div class="card">
                    <div class="card-body text-center">
                        <i class="fas fa-calendar-day fa-3x mb-3"></i> <!-- أيقونة -->
                        <h5 class="card-title">
                            Links to key upcoming or past debates.
                        </h5>
                        <p class="card-text">اطلع على مواعيد المناظرات والأحداث السياسية المقبلة.</p>
                        <a href="https://www.iec.jo/ar/%D8%B1%D9%88%D8%A7%D8%A8%D8%B7-%D9%85%D9%81%D9%8A%D8%AF%D8%A9" class="btn btn-primary">اقرأ المزيد</a> <!-- رابط للتفاصيل -->
                    </div>
                </div>
            </div>

            <!-- البطاقة 3 -->
            <div class="col-md-4">
                <div class="card">
                    <div class="card-body text-center">
                        <i class="fas fa-info-circle fa-3x mb-3"></i> <!-- أيقونة -->
                        <h5 class="card-title">
                            News and updates related to debates.
                        </h5>
                        <p class="card-text">احصل على معلومات إضافية حول المناظرات وكيفية المشاركة.</p>
                        <a href="https://www.iec.jo/ar" class="btn btn-primary">اقرأ المزيد</a> <!-- رابط للتفاصيل -->
                    </div>
                </div>
            </div>
        </div>
    </div>

    <!--<main class="container mt-4">-->
    <!-- قائمة المناظرات -->
    <br /> <br /> <br /> <br /> <br /> <br /> <br />
    <div class="card mb-4">
        <div class="card-header">
            <h2>قائمة المناظرات</h2>
        </div>
        <div class="card-body">
            <p>
                @Html.ActionLink("إنشاء جديد", "Create", "Debates", null, new { @class = "btn btn-primary" })
            </p>
            <table class="table">
                <thead>
                    <tr>
                        <th>@Html.DisplayNameFor(model => model.DebateTitle)</th>
                        <th>@Html.DisplayNameFor(model => model.DebateDate)</th>
                        <th>@Html.DisplayNameFor(model => model.Location)</th>
                        <th>@Html.DisplayNameFor(model => model.Candidate1ID)</th>
                        <th>@Html.DisplayNameFor(model => model.Candidate2ID)</th>
                        <th>@Html.DisplayNameFor(model => model.Description)</th>
                        <th></th>
                    </tr>
                </thead>
                <tbody>
                    @foreach (var item in Model)
                    {
                        <tr>
                            <td>@Html.DisplayFor(modelItem => item.DebateTitle)</td>
                            <td>@Html.DisplayFor(modelItem => item.DebateDate)</td>
                            <td>@Html.DisplayFor(modelItem => item.Location)</td>
                            <td>@Html.DisplayFor(modelItem => item.Candidate1ID)</td>
                            <td>@Html.DisplayFor(modelItem => item.Candidate2ID)</td>
                            <td>@Html.DisplayFor(modelItem => item.Description)</td>
                            <td>
                                @Html.ActionLink("تحرير", "Edit", new { id = item.DebateID }) |
                                @Html.ActionLink("تفاصيل", "Details", new { id = item.DebateID }) |
                                @Html.ActionLink("حذف", "Delete", new { id = item.DebateID })
                            </td>
                        </tr>
                    }
                </tbody>
            </table>
        </div>
    </div>
    @*</main>*@

    <footer class="text-center mt-4">
        <p>&copy; 2024 جميع الحقوق محفوظة.</p>
    </footer>

    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"></script>
    @*<script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.6/dist/umd/popper.min.js"></script>*@
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
</body>
</html>